# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import sys
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA

input_path = sys.argv[1] if len(sys.argv) > 1 else "data_raw.csv"
df = pd.read_csv(input_path)

print(df.head())

df.info()

"""##Stage 1 — Data Cleaning"""

cols_to_drop = [c for c in ["Cabin", "Ticket", "Name", "PassengerId"] if c in df.columns]
df.drop(columns=cols_to_drop, inplace=True)
print(f"  1a. Dropped columns: {cols_to_drop}")

# Impute missing numeric values with median
for col in ["Age", "Fare"]:
    if col in df.columns:
        missing = df[col].isna().sum()
        fill_val = df[col].median()
        #df[col].fillna(fill_val, inplace=True)
        df.fillna({col: fill_val}, inplace=True)

# Impute missing categorical values with mode
for col in ["Embarked"]:
    missing = df["Embarked"].isna().sum()
    mode_val = df["Embarked"].mode()[0]
    df["Embarked"].fillna(mode_val, inplace=True)
    #df["Embarked"].fillna({col: mode_val}, inplace=True)

df_cleaned = df.drop_duplicates()

df = df_cleaned

df.info()

df.head()

"""## STAGE 2 — Feature Transformation"""

# create a gender column and convert male to 1 / female to 0
df["Gender"] = df["Sex"].replace({"male": 1, "female": 0})
df.drop(columns=["Sex"], inplace=True)

df.head()

# One-hot encode Embarked

df = pd.get_dummies(df, columns=['Embarked'] , drop_first=False)
df[['Embarked_C' ,'Embarked_Q', 'Embarked_S'] ] = df[['Embarked_C' ,'Embarked_Q', 'Embarked_S']].astype(int)

df.head()

# Standard-scale numeric features (keep Survived unscaled) keeping the categorical cloumns unchanged

# 1. Identify numeric columns (exclude the target 'Survived')
numeric_cols = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

# 2. Standardize numeric features
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# 3. Confirm scaling
print(f"Scaled {len(numeric_cols)} numeric feature(s): {numeric_cols}")

df.head()

"""##STAGE 3 — Dimensionality Reduction

"""

#Combine SibSp + Parch into FamilySize and drop originals
if "SibSp" in df.columns and "Parch" in df.columns:
    df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
    df.drop(columns=["SibSp", "Parch"], inplace=True)

pre_pca_snapshot = df.copy()

# Apply PCA — keep components that explain >= 90% of variance
target = df["Survived"].copy() if "Survived" in df.columns else None
feature_df = df.drop(columns=["Survived"], errors="ignore")

pca = PCA(n_components=0.90, svd_solver="full", random_state=42)
pca_array = pca.fit_transform(feature_df)
n_components = pca.n_components_
pca_cols = [f"PC{i+1}" for i in range(n_components)]
df = pd.DataFrame(pca_array, columns=pca_cols)

df['Survived'] = target

df.head()

"""##STAGE 4 — Discretization"""

#  Bin Age into life-stage groups
if "Age" in pre_pca_snapshot.columns:
    age_bins   = [0, 12, 18, 35, 60, np.inf]
    age_labels = ["Child", "Teen", "YoungAdult", "Adult", "Senior"]
    df["Age_Group"] = pd.cut(
        pre_pca_snapshot["Age"], bins=age_bins, labels=age_labels, right=False
    ).astype(str)

#  Bin Fare into 4 quartile bands
if "Fare" in pre_pca_snapshot.columns:
    df["Fare_Band"] = pd.qcut(
        pre_pca_snapshot["Fare"], q=3,
        labels=["Low", "Mid", "High"],
        duplicates="drop"
    ).astype(str)

# Bin FamilySize into Solo / Small / Large
if "FamilySize" in pre_pca_snapshot.columns:
    family_bins   = [0, 1, 4, np.inf]
    family_labels = ["Solo", "Small", "Large"]
    df["Family_Group"] = pd.cut(
        pre_pca_snapshot["FamilySize"], bins=family_bins,
        labels=family_labels, right=True
    ).astype(str)

df = df.dropna()

le = LabelEncoder()

df["Age_Group"] = le.fit_transform(df["Age_Group"])
df["Fare_Band"] = le.fit_transform(df["Fare_Band"])
df["Family_Group"] = le.fit_transform(df["Family_Group"])

print(df.dtypes)

"""##Save Output"""

output_path = "data_preprocessed.csv"
df.to_csv(output_path, index=False)

import os
import subprocess

#Handoff to next script
next_script = "analytics.py"
if os.path.exists(next_script):
    print(f"Handing off to {next_script} …")
    subprocess.run([sys.executable, next_script, output_path], check=True)
else:
    print(f"'{next_script}' not found — skipping handoff")